FROM debian:buster

RUN apt-get update \
 && apt-get install -y \
    charybdis

RUN adduser --system --group --disabled-login charybdis
USER charybdis

ENTRYPOINT ["charybdis", "-foreground"]
#CMD ["overrideable-args-go-here"]
