FROM debian:buster

RUN apt-get update \
 && apt-get install -y \
    atheme-services

RUN adduser --system --group --disabled-login atheme
USER atheme

ENTRYPOINT ["atheme-services", "-n"]
#CMD ["overrideable-args-go-here"]
